---
# tasks file for package-react-ui

- name: Get username of User running deploy
  become: false
  local_action: command whoami
  register: logged_in_user
  tags: ["ui", "localhost"]

- name: Clear dist Folders
  file:
    state: absent
    path: "{{ base_projects_path }}/{{ item }}/{{ dist_folder }}"
  with_items: "{{ projects }}"
  become: yes
  become_user: "{{ logged_in_user.stdout }}"
  tags: ["ui", "localhost"]

- name: Build projects and generate zip folder
  command: "npm run zip --prefix {{ base_projects_path }}/{{ item }}"
  with_items: "{{ projects }}"
  become: yes
  become_user: "{{ logged_in_user.stdout }}"
  tags: ["ui", "localhost"]
